name: AuthSystem
version: '1.1.0'
main: com.authsystem.AuthSystem
api-version: '26.2'
author: Matheus
load: POSTWORLD
depend:
  - packetevents
description: Sistema de autenticacao premium/cracked com verificacao criptografica via Mojang.

commands:
  login:
    description: Efetua login na sua conta
    usage: /login <senha>
  registro:
    description: Cria uma nova conta
    usage: /registro <senha> <confirmar-senha>
    aliases: [register, cadastrar]
